// AFTER HOURS — ground detail kit shared by the four stops: alpha "decal" atlases (stains, chalk drawings, leaves, footprints, ...) scattered as instanced quads
// and instanced grass / beach-grass tufts with wind. Everything is drawn in 2D canvases (no assets); one InstancedMesh per decal type per cell.
import * as THREE from 'three';
import { std } from '../../core/mats.js';
import { canvasTexture } from '../../core/canvas2d.js';
import { makeRng } from '../../core/util.js';
import { geo, TAU, PI } from './common.js';

const CELL = 128, GRID = 4;
/** Build a 4x4 atlas (512 px) from an array of up to 16 painter functions painter(ctx, w, h, rng). Returns {tex, mat}. */
export function decalAtlas(name, painters, { rough = 0.9, seed = 1, emissive = 0, env = 1 } = {}) {
  const tex = canvasTexture(CELL * GRID, CELL * GRID, (c) => {
    c.clearRect(0, 0, CELL * GRID, CELL * GRID);
    painters.forEach((p, i) => { if (!p) return; const r = makeRng(seed * 131 + i * 17 + 3); c.save(); c.translate((i % GRID) * CELL, Math.floor(i / GRID) * CELL); c.beginPath(); c.rect(0, 0, CELL, CELL); c.clip(); p(c, CELL, CELL, r); c.restore(); });
  }, { srgb: true, aniso: 8 });
  const mat = std({ map: tex, transparent: true, depthWrite: false, roughness: rough, metalness: 0, envMapIntensity: env, polygonOffset: true, polygonOffsetFactor: -3, polygonOffsetUnits: -3, key: 'decal', ...(emissive ? { emissive: 0xffffff, emissiveMap: tex, emissiveIntensity: emissive } : {}) });
  return { tex, mat, name };
}
const _m4 = new THREE.Matrix4(), _v3 = new THREE.Vector3();
/** append one quad (already in world/local-stop coordinates via matrix m; local quad w x h in the XZ plane (flat) or XY plane (vertical)) for atlas cell `cell` to the accumulator */
const pushQuad = (acc, m, w, h, cell, vertical, dz = 0, dy = 0) => {
  const u0 = (cell % GRID) / GRID, v0 = 1 - (Math.floor(cell / GRID) + 1) / GRID, s = 1 / GRID, base = acc.pos.length / 3;
  const c = [[-0.5, -0.5, 0, 1], [0.5, -0.5, 1, 1], [0.5, 0.5, 1, 0], [-0.5, 0.5, 0, 0]];   // x, y in quad space, u, (1-v)
  for (const [qx, qy, u, vv] of c) { if (vertical) _v3.set(qx * w, qy * h + dy, dz); else _v3.set(qx * w, 0, -qy * h); _v3.applyMatrix4(m); acc.pos.push(_v3.x, _v3.y, _v3.z); acc.uv.push(u0 + u * s, v0 + (1 - vv) * s); }
  acc.idx.push(base, base + 1, base + 2, base, base + 2, base + 3);
};
const acc = (atlas, key) => (atlas._acc ||= {})[key] ||= { pos: [], uv: [], idx: [] };
const flush = (B, atlas, key) => { const a = atlas._acc && atlas._acc[key]; if (!a || !a.pos.length) return; const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(a.pos, 3)); g.setAttribute('uv', new THREE.Float32BufferAttribute(a.uv, 2)); g.setIndex(a.idx); const nrm = new Float32Array(a.pos.length); for (let i = 0; i < nrm.length; i += 3) nrm[i + 1] = 1; if (key === 'flat') g.setAttribute('normal', new THREE.BufferAttribute(nrm, 3)); else g.computeVertexNormals(); g.computeBoundingSphere();
  const mesh = new THREE.Mesh(g, atlas.mat); mesh.castShadow = false; mesh.receiveShadow = true; mesh.matrixAutoUpdate = false; mesh.renderOrder = 2; B.group.add(mesh); delete atlas._acc[key]; };
/** Place flat ground decals as ONE merged mesh per call: list of [x, y, z, size, cell, rotation(rad), tint(unused), aspect=1]. y is the surface height. */
export function placeDecals(B, atlas, list) {
  const a = acc(atlas, 'flat'); for (const [x, y, z, size, cell, rot = 0, , asp = 1] of list) { _m4.compose(new THREE.Vector3(x, y + 0.018, z), new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), rot), new THREE.Vector3(1, 1, 1)); pushQuad(a, _m4, size * asp, size, cell, false); }
  flush(B, atlas, 'flat');
}
/** Vertical decal (e.g. tombstone engraving) glued to a host instance: quad w x h centred at (0, y, z) in the host's local frame, transformed by the host matrix. Call flushVertical() once at the end. */
export function placeVertical(B, atlas, cell, matrix, tint, [w, h, dy, dz]) { pushQuad(acc(atlas, 'vert'), matrix, w, h, cell, true, dz, dy); }
export const flushVertical = (B, atlas) => flush(B, atlas, 'vert');

// ------------------------------------------------------------------ painter helpers
export const blob = (c, x, y, r, col, a = 1, n = 9, rng = Math.random, jit = 0.35) => { c.fillStyle = col; c.globalAlpha = a; c.beginPath(); for (let i = 0; i <= n; i++) { const ang = i / n * TAU, rr = r * (1 - jit + rng() * jit * 2); const px = x + Math.cos(ang) * rr, py = y + Math.sin(ang) * rr; if (i === 0) c.moveTo(px, py); else c.quadraticCurveTo(x + Math.cos(ang - TAU / n / 2) * rr * 1.1, y + Math.sin(ang - TAU / n / 2) * rr * 1.1, px, py); } c.closePath(); c.fill(); c.globalAlpha = 1; };
export const soft = (c, x, y, r, col, a) => { const g = c.createRadialGradient(x, y, 0, x, y, r); g.addColorStop(0, col.replace('A', String(a))); g.addColorStop(1, col.replace('A', '0')); c.fillStyle = g; c.fillRect(x - r, y - r, r * 2, r * 2); };
export const PAINT = {
  leaf: (col, dark) => (c, w, h, r) => { for (let i = 0; i < 7; i++) { c.save(); c.translate(w * (0.15 + r() * 0.7), h * (0.15 + r() * 0.7)); c.rotate(r() * TAU); const s = 9 + r() * 10; c.fillStyle = r() < 0.5 ? col : dark; c.beginPath(); c.moveTo(-s, 0); c.quadraticCurveTo(0, -s * 0.7, s, 0); c.quadraticCurveTo(0, s * 0.7, -s, 0); c.fill(); c.strokeStyle = 'rgba(30,18,8,0.6)'; c.lineWidth = 1; c.beginPath(); c.moveTo(-s, 0); c.lineTo(s * 0.9, 0); c.stroke(); c.restore(); } },
  stain: (col, a = 0.55) => (c, w, h, r) => { for (let k = 0; k < 4; k++) blob(c, w * (0.3 + r() * 0.4), h * (0.3 + r() * 0.4), 14 + r() * 22, col, a * (0.4 + r() * 0.6), 9, r, 0.45); for (let k = 0; k < 9; k++) blob(c, w * (0.1 + r() * 0.8), h * (0.1 + r() * 0.8), 1.5 + r() * 4, col, a, 6, r, 0.3); },
  scuff: (c, w, h, r) => { c.strokeStyle = 'rgba(20,20,26,0.5)'; for (let i = 0; i < 9; i++) { c.lineWidth = 1 + r() * 3; c.globalAlpha = 0.25 + r() * 0.5; c.beginPath(); const x = w * (0.1 + r() * 0.8), y = h * (0.1 + r() * 0.8), a = r() * 0.6 - 0.3; c.moveTo(x, y); c.quadraticCurveTo(x + 20, y + 10 * a, x + 40 + r() * 20, y + 30 * a); c.stroke(); } c.globalAlpha = 1; },
  crack: (c, w, h, r) => { c.strokeStyle = 'rgba(8,8,10,0.85)'; c.lineCap = 'round'; const br = (x, y, a, len, wd) => { if (len < 6 || wd < 0.4) return; c.lineWidth = wd; c.beginPath(); c.moveTo(x, y); const x2 = x + Math.cos(a) * len, y2 = y + Math.sin(a) * len; c.quadraticCurveTo((x + x2) / 2 + (r() - 0.5) * 10, (y + y2) / 2 + (r() - 0.5) * 10, x2, y2); c.stroke(); br(x2, y2, a + (r() - 0.5) * 0.9, len * 0.7, wd * 0.75); if (r() < 0.6) br(x2, y2, a + (r() < 0.5 ? 1 : -1) * (0.5 + r() * 0.7), len * 0.55, wd * 0.6); }; br(10 + r() * 20, h * (0.3 + r() * 0.4), (r() - 0.5) * 0.7, 40, 2.4); },
  footprint: (col = 'rgba(40,30,20,0.55)', bare = true) => (c, w, h, r) => { for (let i = 0; i < 4; i++) { const x = w * (i % 2 ? 0.62 : 0.36), y = h * (0.14 + i * 0.22); c.save(); c.translate(x, y); c.rotate((r() - 0.5) * 0.2); c.fillStyle = col; if (bare) { c.beginPath(); c.ellipse(0, 6, 8, 13, 0, 0, TAU); c.fill(); c.beginPath(); c.ellipse(0, -13, 7, 6, 0, 0, TAU); c.fill(); for (let t = 0; t < 4; t++) { c.beginPath(); c.arc(-8 + t * 5.4, -22 + Math.abs(t - 1.5) * 2.5, 2.6 - t * 0.2, 0, TAU); c.fill(); } } else { c.beginPath(); c.roundRect(-8, -14, 16, 34, 6); c.fill(); c.fillStyle = 'rgba(0,0,0,0.25)'; for (let t = 0; t < 4; t++) c.fillRect(-7, -10 + t * 7, 14, 2); } c.restore(); } },
  moss: (c, w, h, r) => { for (let k = 0; k < 26; k++) blob(c, w * (0.15 + r() * 0.7), h * (0.15 + r() * 0.7), 5 + r() * 11, r() < 0.5 ? 'rgb(52,84,36)' : 'rgb(38,62,28)', 0.28 + r() * 0.4, 8, r, 0.4); },
  chalkHop: (c, w, h, r) => { c.strokeStyle = 'rgba(210,214,226,0.7)'; c.lineWidth = 3; c.lineCap = 'round'; const sq = 20, x0 = w / 2 - sq / 2; let y = h - 12; const cells = [[0, 1], [0, 1], [-1, 2], [0, 1], [-1, 2], [0, 1]]; c.font = '700 13px "Liberation Sans", sans-serif'; c.fillStyle = 'rgba(210,214,226,0.72)'; c.textAlign = 'center'; cells.forEach(([off, n], i) => { for (let k = 0; k < n; k++) { const x = x0 + (n === 2 ? (k - 0.5) * sq : 0) - (n === 2 ? 0 : 0) + (r() - 0.5); c.strokeRect(x + (r() - 0.5), y - sq, sq, sq); c.fillText(String(i * 1 + 1 + (n === 2 ? k : 0)), x + sq / 2, y - 5); } y -= sq + 1; }); },
  chalkHeart: (col = 'rgba(255,150,190,0.85)') => (c, w, h, r) => { c.strokeStyle = col; c.lineWidth = 4; c.lineCap = 'round'; c.beginPath(); c.moveTo(w / 2, h * 0.78); c.bezierCurveTo(w * 0.05, h * 0.5, w * 0.25, h * 0.1, w / 2, h * 0.36); c.bezierCurveTo(w * 0.75, h * 0.1, w * 0.95, h * 0.5, w / 2, h * 0.78); c.stroke(); c.lineWidth = 2.5; c.beginPath(); c.moveTo(w * 0.42, h * 0.5); c.lineTo(w * 0.58, h * 0.5); c.stroke(); },
  chalkSun: (c, w, h, r) => { c.strokeStyle = 'rgba(214,186,96,0.8)'; c.lineWidth = 4; c.lineCap = 'round'; c.beginPath(); c.arc(w / 2, h / 2, 18, 0, TAU); c.stroke(); for (let i = 0; i < 12; i++) { const a = i / 12 * TAU; c.beginPath(); c.moveTo(w / 2 + Math.cos(a) * 26, h / 2 + Math.sin(a) * 26); c.lineTo(w / 2 + Math.cos(a) * (36 + (i % 2) * 6), h / 2 + Math.sin(a) * (36 + (i % 2) * 6)); c.stroke(); } c.beginPath(); c.arc(w / 2 - 6, h / 2 - 4, 1.5, 0, TAU); c.arc(w / 2 + 6, h / 2 - 4, 1.5, 0, TAU); c.stroke(); c.beginPath(); c.arc(w / 2, h / 2 + 3, 8, 0.2, PI - 0.2); c.stroke(); },
  confetti: (c, w, h, r) => { const cols = ['#c83a80', '#2ea8bc', '#c8a02c', '#5a44c8', '#3ab070', '#b8b8b8']; for (let i = 0; i < 46; i++) { c.save(); c.translate(w / 2 + (r() - 0.5) * w * 0.85, h / 2 + (r() - 0.5) * h * 0.85); c.rotate(r() * TAU); c.fillStyle = cols[Math.floor(r() * cols.length)]; c.globalAlpha = 0.6 + r() * 0.4; c.fillRect(-3, -1.5, 6 + r() * 3, 3); c.restore(); } c.globalAlpha = 1; },
  gum: (c, w, h, r) => { for (let i = 0; i < 12; i++) blob(c, w * (0.1 + r() * 0.8), h * (0.1 + r() * 0.8), 2 + r() * 3.5, r() < 0.75 ? 'rgba(52,48,46,0.9)' : 'rgba(120,70,84,0.85)', 1, 6, r, 0.25); },
  hazard: (a = '#ffd23a', b = '#15151a') => (c, w, h) => { c.fillStyle = b; c.fillRect(0, h * 0.38, w, h * 0.24); c.fillStyle = a; for (let x = -h; x < w + h; x += 22) { c.beginPath(); c.moveTo(x, h * 0.62); c.lineTo(x + 11, h * 0.62); c.lineTo(x + 11 + h * 0.24, h * 0.38); c.lineTo(x + h * 0.24, h * 0.38); c.fill(); } c.strokeStyle = 'rgba(0,0,0,0.35)'; c.lineWidth = 2; c.strokeRect(1, h * 0.38, w - 2, h * 0.24); },
  splat: (col) => (c, w, h, r) => { blob(c, w / 2, h / 2, 16 + r() * 8, col, 0.85, 12, r, 0.5); for (let i = 0; i < 16; i++) { const a = r() * TAU, d = 24 + r() * 32; blob(c, w / 2 + Math.cos(a) * d, h / 2 + Math.sin(a) * d, 1.5 + r() * 4, col, 0.85, 6, r, 0.3); c.strokeStyle = col; c.lineWidth = 1.2; c.globalAlpha = 0.6; c.beginPath(); c.moveTo(w / 2 + Math.cos(a) * 14, h / 2 + Math.sin(a) * 14); c.lineTo(w / 2 + Math.cos(a) * (d - 3), h / 2 + Math.sin(a) * (d - 3)); c.stroke(); c.globalAlpha = 1; } },
  bones: (c, w, h, r) => { for (let i = 0; i < 4; i++) { c.save(); c.translate(w * (0.2 + r() * 0.6), h * (0.2 + r() * 0.6)); c.rotate(r() * TAU); c.fillStyle = '#d9d0b6'; const L = 14 + r() * 12; c.fillRect(-L / 2, -2.2, L, 4.4); for (const s of [-1, 1]) { c.beginPath(); c.arc(s * L / 2, -3, 3.4, 0, TAU); c.arc(s * L / 2, 3, 3.4, 0, TAU); c.fill(); } c.restore(); } c.fillStyle = '#e4dcc4'; c.beginPath(); c.ellipse(w * 0.55, h * 0.4, 9, 8, 0.3, 0, TAU); c.fill(); c.fillStyle = '#1a1512'; c.beginPath(); c.arc(w * 0.55 - 3.5, h * 0.4 - 1, 2.2, 0, TAU); c.arc(w * 0.55 + 3.5, h * 0.4 - 1, 2.2, 0, TAU); c.fill(); },
  wax: (c, w, h, r) => { blob(c, w / 2, h / 2, 12, 'rgba(235,225,200,0.9)', 1, 9, r, 0.4); for (let i = 0; i < 5; i++) blob(c, w / 2 + (r() - 0.5) * 34, h / 2 + (r() - 0.5) * 34, 3 + r() * 4, 'rgba(230,220,195,0.85)', 1, 6, r, 0.3); },
  starfish: (c, w, h, r) => { c.save(); c.translate(w / 2, h / 2); c.rotate(r() * TAU); c.fillStyle = 'rgba(232,120,70,0.95)'; c.beginPath(); for (let i = 0; i < 10; i++) { const a = i / 10 * TAU - PI / 2, rr = i % 2 ? 9 : 26; c.lineTo(Math.cos(a) * rr, Math.sin(a) * rr); } c.closePath(); c.fill(); c.fillStyle = 'rgba(255,190,140,0.85)'; for (let i = 0; i < 5; i++) { const a = i / 5 * TAU - PI / 2; for (let k = 1; k < 4; k++) { c.beginPath(); c.arc(Math.cos(a) * k * 6, Math.sin(a) * k * 6, 1.4, 0, TAU); c.fill(); } } c.restore(); },
  seaweed: (c, w, h, r) => { for (let i = 0; i < 12; i++) { c.strokeStyle = r() < 0.5 ? 'rgba(38,70,34,0.9)' : 'rgba(58,84,36,0.9)'; c.lineWidth = 2 + r() * 2.4; c.lineCap = 'round'; c.beginPath(); const x = w * (0.1 + r() * 0.8), y = h * (0.2 + r() * 0.6); c.moveTo(x, y); c.bezierCurveTo(x + (r() - 0.5) * 40, y + 18, x + (r() - 0.5) * 50, y + 30, x + (r() - 0.5) * 36, y + 44 + r() * 20); c.stroke(); } },
  crabTrack: (c, w, h, r) => { c.fillStyle = 'rgba(30,24,16,0.55)'; for (let i = 0; i < 16; i++) { const x = w * 0.15 + i * 6 + (r() - 0.5) * 3, y = h / 2 + (i % 2 ? 6 : -6) + Math.sin(i * 0.6) * 10; for (const dy of [-3, 0, 3]) { c.beginPath(); c.arc(x, y + dy, 1.5, 0, TAU); c.fill(); } } },
  coins: (c, w, h, r) => { for (let i = 0; i < 9; i++) { const x = w * (0.15 + r() * 0.7), y = h * (0.15 + r() * 0.7); c.fillStyle = 'rgba(255,210,80,0.95)'; c.beginPath(); c.ellipse(x, y, 6, 5, r(), 0, TAU); c.fill(); c.strokeStyle = 'rgba(150,100,10,0.9)'; c.lineWidth = 1; c.stroke(); } },
  tar: (c, w, h, r) => { blob(c, w / 2, h * 0.4, 20, 'rgba(12,10,8,0.9)', 1, 10, r, 0.4); for (let i = 0; i < 4; i++) { c.fillStyle = 'rgba(12,10,8,0.85)'; c.fillRect(w * (0.3 + i * 0.13), h * 0.4, 5, 24 + r() * 26); } },
  drain: (c, w, h) => { c.fillStyle = 'rgba(14,14,16,0.92)'; c.fillRect(w * 0.15, h * 0.3, w * 0.7, h * 0.4); c.fillStyle = 'rgba(90,92,96,0.95)'; for (let i = 0; i < 9; i++) c.fillRect(w * 0.15 + 4 + i * (w * 0.7 - 8) / 9, h * 0.3 + 3, 5, h * 0.4 - 6); c.strokeStyle = 'rgba(60,62,66,0.95)'; c.lineWidth = 3; c.strokeRect(w * 0.15, h * 0.3, w * 0.7, h * 0.4); },
  ticket: (c, w, h, r) => { for (let i = 0; i < 3; i++) { c.save(); c.translate(w * (0.25 + r() * 0.5), h * (0.25 + r() * 0.5)); c.rotate(r() * TAU); c.fillStyle = ['rgba(250,230,150,0.95)', 'rgba(250,120,140,0.95)', 'rgba(150,230,240,0.95)'][i % 3]; c.fillRect(-13, -7, 26, 14); c.fillStyle = 'rgba(40,30,20,0.7)'; c.fillRect(-9, -3, 18, 2); c.fillRect(-9, 1, 12, 2); c.restore(); } },
  puddle: (tint = [12, 14, 26]) => (c, w, h, r) => { c.save(); c.shadowColor = 'rgba(0,0,0,0.55)'; c.shadowBlur = 7; blob(c, w / 2, h / 2, 44, `rgba(${tint[0]},${tint[1]},${tint[2]},0.9)`, 1, 15, r, 0.3); c.restore(); blob(c, w / 2 + (r() - 0.5) * 8, h / 2 + (r() - 0.5) * 8, 26, `rgba(${tint[0] + 40},${tint[1] + 46},${tint[2] + 70},0.28)`, 1, 11, r, 0.3); c.strokeStyle = 'rgba(190,200,225,0.14)'; c.lineWidth = 1.4; c.beginPath(); c.ellipse(w / 2 + 3, h / 2 + 2, 40, 33, 0.3, 0.3, 2.4); c.stroke(); },
  puddleRim: (c, w, h, r) => { soft(c, w / 2, h / 2, w * 0.5, 'rgba(10,10,14,A)', 0.55); },
};

// ------------------------------------------------------------------ grass tufts
const tuftTex = (name, cols, { blades = 16, height = 0.9, dry = 0 } = {}) => canvasTexture(128, 128, (c, w, h) => {
  const r = makeRng(name.length * 977 + 5); c.clearRect(0, 0, w, h);
  for (let i = 0; i < blades; i++) { const x = w * (0.08 + r() * 0.84), tipx = x + (r() - 0.5) * w * 0.5, ht = h * (0.45 + r() * 0.5) * height, wd = 2.6 + r() * 3.2; const col = cols[Math.floor(r() * cols.length)]; const g = c.createLinearGradient(0, h, 0, h - ht); g.addColorStop(0, 'rgba(14,20,8,1)'); g.addColorStop(0.35, col); g.addColorStop(1, dry > r() ? 'rgba(150,130,70,1)' : col);
    c.fillStyle = g; c.beginPath(); c.moveTo(x - wd, h); c.quadraticCurveTo(x - wd * 0.4, h - ht * 0.55, tipx, h - ht); c.quadraticCurveTo(x + wd * 0.4, h - ht * 0.55, x + wd, h); c.closePath(); c.fill(); }
}, { srgb: true, aniso: 4 });
/** Grass / weed tufts: crossed quads, alpha-tested, wind-swayed. area: [x0,z0,x1,z1]; ok(x,z)->bool; heightFn(x,z)->y. Returns count. */
export function grassTufts(B, RC, { name = 'grass', n = 1500, area, ok = () => true, heightFn = () => 0, size = [0.7, 1.3], cols = ['#3c5a24', '#4a6a2a', '#345020'], tints = [0xffffff, 0xd8e0c0, 0xc0c8a0, 0xa0a888], dry = 0.2, amp = 0.1 }) {
  const tex = tuftTex(name, cols, { dry }); const mat = std({ map: tex, roughness: 0.92, side: THREE.DoubleSide, alphaTest: 0.45, alphaToCoverage: true, key: 'tuft' + name, wind: { amp, freq: 1.7, stiff: 'uv' } });
  const g = geo('tuft' + name, () => { const parts = []; for (let k = 0; k < 3; k++) { const p = new THREE.PlaneGeometry(0.55, 0.5, 1, 2); p.translate(0, 0.25, 0); p.rotateY(k * PI / 3); parts.push(p); } const m = new THREE.BufferGeometry(); const pos = [], uv = [], nrm = [], idx = []; let base = 0; for (const p of parts) { const P = p.attributes.position, U = p.attributes.uv, N = p.attributes.normal; for (let i = 0; i < P.count; i++) { pos.push(P.getX(i), P.getY(i), P.getZ(i)); uv.push(U.getX(i), U.getY(i)); nrm.push(0, 1, 0); } for (const i of p.index.array) idx.push(base + i); base += P.count; } m.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); m.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2)); m.setAttribute('normal', new THREE.Float32BufferAttribute(nrm, 3)); m.setIndex(idx); return m; });
  let cnt = 0; for (let i = 0; i < n * 3 && cnt < n; i++) { const x = area[0] + RC() * (area[2] - area[0]), z = area[1] + RC() * (area[3] - area[1]); if (!ok(x, z)) continue; const s = size[0] + RC() * (size[1] - size[0]); B.instance('tuft' + name, g, mat, B.matrix([x, heightFn(x, z) - 0.02, z], RC() * TAU, [s * (0.8 + RC() * 0.5), s * (0.7 + RC() * 0.7), s * (0.8 + RC() * 0.5)]), tints[Math.floor(RC() * tints.length)], { cast: false }); cnt++; }
  return cnt;
}

// ------------------------------------------------------------------ tombstone engravings (dark carving + pale lower highlight), 128 px cells
const carve = (c, draw) => { c.save(); c.translate(0, 1.6); c.fillStyle = c.strokeStyle = 'rgba(235,240,230,0.30)'; draw(); c.restore(); c.fillStyle = c.strokeStyle = 'rgba(8,10,8,0.96)'; draw(); };
export const ENGRAVE = [
  (c, w, h) => carve(c, () => { c.lineWidth = 5; c.lineCap = 'round'; c.beginPath(); c.moveTo(w / 2, 14); c.lineTo(w / 2, 62); c.moveTo(w / 2 - 15, 28); c.lineTo(w / 2 + 15, 28); c.stroke(); c.font = '700 22px "Liberation Serif", serif'; c.textAlign = 'center'; c.fillText('R.I.P.', w / 2, 92); c.lineWidth = 2; c.beginPath(); c.moveTo(w / 2 - 26, 102); c.lineTo(w / 2 + 26, 102); c.stroke(); }),
  (c, w, h) => carve(c, () => { c.beginPath(); c.ellipse(w / 2, 40, 18, 16, 0, 0, TAU); c.fill(); c.fillRect(w / 2 - 10, 50, 20, 14); c.globalCompositeOperation = 'destination-out'; c.beginPath(); c.arc(w / 2 - 7, 39, 4.6, 0, TAU); c.arc(w / 2 + 7, 39, 4.6, 0, TAU); c.fill(); c.fillRect(w / 2 - 2, 48, 4, 8); c.globalCompositeOperation = 'source-over'; c.lineWidth = 5; c.lineCap = 'round'; c.beginPath(); c.moveTo(w / 2 - 28, 74); c.lineTo(w / 2 + 28, 96); c.moveTo(w / 2 + 28, 74); c.lineTo(w / 2 - 28, 96); c.stroke(); }),
  (c, w, h) => carve(c, () => { c.font = '700 15px "Liberation Serif", serif'; c.textAlign = 'center'; c.fillText('HERE LIES', w / 2, 26); c.font = '700 19px "Liberation Serif", serif'; c.fillText(['ISADORA','MORTIMER','CORNELIUS','AGATHA','BARNABY'][Math.floor(Math.random() * 5)], w / 2, 54); c.font = '700 13px "Liberation Serif", serif'; c.fillText('1897 - 1931', w / 2, 76); c.lineWidth = 2; c.beginPath(); c.moveTo(w / 2 - 30, 88); c.quadraticCurveTo(w / 2, 100, w / 2 + 30, 88); c.stroke(); }),
  (c, w, h) => carve(c, () => { c.lineWidth = 4; c.lineCap = 'round'; for (const s of [-1, 1]) { c.beginPath(); c.moveTo(w / 2, 90); c.quadraticCurveTo(w / 2 + s * 36, 74, w / 2 + s * 34, 30); c.quadraticCurveTo(w / 2 + s * 26, 52, w / 2 + s * 14, 50); c.quadraticCurveTo(w / 2 + s * 18, 66, w / 2, 70); c.stroke(); } c.beginPath(); c.arc(w / 2, 34, 8, 0, TAU); c.fill(); }),
  (c, w, h) => carve(c, () => { c.font = '700 14px "Liberation Serif", serif'; c.textAlign = 'center'; c.fillText('BELOVED', w / 2, 34); c.fillText('GHOUL', w / 2, 54); c.lineWidth = 3; c.beginPath(); c.arc(w / 2, 82, 12, 0, TAU); c.stroke(); c.beginPath(); c.moveTo(w / 2, 70); c.lineTo(w / 2, 94); c.moveTo(w / 2 - 12, 82); c.lineTo(w / 2 + 12, 82); c.stroke(); }),
];
