// Ready-made ambience recipes for all 16 stops (+ menu). Positions are stop-local (the ambience origin is added). Use as
//   audio.ambience.set('shaft-nine.surface', 2.5)   or   audio.ambience.set(stop.data.ambient)  (recipes authored by the stop follow the same DSL)
// Each stop has a distinct bed mix (wind character, machinery, water, music, crackle) and its own event vocabulary. Levels are calibrated by tools/audio-analyze.mjs:
// gain = per-recipe fader (whole ambience ~ -32 dBFS rms), eventGain = one-shots relative to the beds; a bed with gain 1 sits at about -24 dBFS rms.
const W = (o) => ({ type: 'wind', ...o });
export const PRESETS = {
  // ------------------------------------------------------------------------------------------------ SHAFT NINE
  'shaft-nine.surface': { space: 'openDusk', gain: 0.65, rooms: [{ space: 'hutInterior', meanMax: 7, ceilMax: 8 }], eventGain: 1.0, beds: [
    W({ speed: 0.42, gust: 0.45, whistle: 0.35, howl: 0.12, gain: 0.5 }), { type: 'hum', freq: 50, harmonics: 10, buzz: 0.6, gain: 0.09, pos: [12, 8, -8] },
    { type: 'machine', kind: 'steam', rpm: 150, gain: 0.1, pos: [6, 6.5, -24] }, { type: 'crackle', kind: 'fire', intensity: 0.5, gain: 0.16, pos: [-21.5, 1.2, -1.5] }, { type: 'insects', freq: 4300, density: 0.5, gain: 0.05 } ],
    events: [{ type: 'creak', every: [6, 16] }, { type: 'crow', every: [12, 30] }, { type: 'clank', every: [8, 20] }, { type: 'rockfall', every: [40, 90], pos: 'far', gain: 0.7 }, { type: 'radio', every: [45, 100], pos: [-27, 2, -8], gain: 0.7 }, { type: 'pipe', every: [25, 60] }, { type: 'whistle', every: [60, 140], pos: 'far', gain: 0.7 }] },
  'shaft-nine.tunnels': { space: 'tunnel', gain: 0.268, rooms: [{ space: 'tunnelHall', meanMin: 10 }], eventGain: 0.8, beds: [
    W({ speed: 0.16, gust: 0.15, whistle: 0, howl: 0.65, gain: 0.3, follow: false }), { type: 'rumble', freq: 70, throb: 0.25, depth: 0.5, rate: 0.11, gain: 0.8, sub: 32 }, { type: 'machine', kind: 'pump', rpm: 170, gain: 0.1 },
    { type: 'hum', freq: 100, harmonics: 6, buzz: 0.8, gain: 0.04 }, { type: 'water', kind: 'drip', rate: 0.7, gain: 0.9 }, { type: 'water', kind: 'stream', intensity: 0.25, gain: 0.07 } ],
    events: [{ type: 'creak', every: [3, 9] }, { type: 'rockfall', every: [30, 70], gain: 0.7 }, { type: 'pipe', every: [15, 40] }, { type: 'scurry', every: [12, 30] }, { type: 'clank', every: [20, 50], pos: 'far' }, { type: 'moan-far', every: [45, 110], gain: 0.6 }, { type: 'metal-groan', every: [40, 90], pos: 'far' }] },
  'shaft-nine.flooded': { space: 'flooded', gain: 0.432, eventGain: 0.5, beds: [
    { type: 'water', kind: 'lap', intensity: 0.55, gain: 0.34 }, { type: 'rumble', freq: 55, throb: 0.2, depth: 0.4, gain: 0.65 }, { type: 'machine', kind: 'pump', rpm: 140, gain: 0.13 }, { type: 'hum', freq: 120, harmonics: 6, buzz: 0.2, gain: 0.035 },
    { type: 'water', kind: 'bubbles', intensity: 0.3, gain: 0.09 }, { type: 'drone', freq: 41, chord: [1, 1.5, 2.01], movement: 0.6, bright: 700, gain: 0.06 } ],
    events: [{ type: 'drip', every: [1.2, 3] }, { type: 'splash', every: [5, 12] }, { type: 'bubble', every: [4, 11] }, { type: 'creak', every: [6, 14] }, { type: 'pipe', every: [10, 30] }, { type: 'metal-groan', every: [25, 60], pos: 'far' }, { type: 'moan-far', every: [50, 120], gain: 0.5 }] },
  'shaft-nine.crystal': { space: 'crystalCavern', gain: 0.891, eventGain: 0.6, beds: [
    { type: 'drone', freq: 110, chord: [1, 1.5, 2, 3, 4.03], movement: 0.8, bright: 5200, detune: 14, gain: 0.26 }, { type: 'hum', freq: 220, harmonics: 12, buzz: 0.1, color: 0.9, gain: 0.05 }, W({ speed: 0.1, gust: 0.1, whistle: 0.5, howl: 0.3, gain: 0.1, follow: false }), { type: 'water', kind: 'drip', rate: 0.35, gain: 0.7 } ],
    events: [{ type: 'chime', every: [3, 9], gain: 0.8 }, { type: 'ping', every: [12, 30] }, { type: 'drip', every: [2, 6] }, { type: 'ice-crack', every: [30, 80], pos: 'far', gain: 0.6 }, { type: 'rockfall', every: [50, 110], pos: 'far', gain: 0.6 }] },
  'shaft-nine.magma': { space: 'magmaChamber', gain: 0.129, eventGain: 0.5, beds: [
    { type: 'crackle', kind: 'fire', intensity: 0.9, gain: 0.38 }, { type: 'rumble', freq: 55, throb: 0.5, depth: 0.6, rate: 0.17, gain: 1.5, sub: 38 }, { type: 'water', kind: 'bubbles', intensity: 0.8, low: true, gain: 0.36 }, { type: 'water', kind: 'hiss', gain: 0.189 }, { type: 'noise', color: 'brown', lp: 200, mod: 0.3, depth: 0.5, gain: 0.48 } ],
    events: [{ type: 'boom', every: [15, 40], pos: 'far' }, { type: 'rockfall', every: [10, 30] }, { type: 'steam', every: [6, 16] }, { type: 'pop', every: [3, 9] }, { type: 'ping', every: [8, 20], gain: 0.6 }, { type: 'metal-groan', every: [30, 70], pos: 'far' }] },
  // ------------------------------------------------------------------------------------------------ WHITEOUT
  'whiteout.village': { space: 'snow', gain: 0.272, rooms: [{ space: 'hutInterior', meanMax: 6, ceilMax: 7 }], eventGain: 4, beds: [
    W({ speed: 0.78, gust: 0.7, whistle: 0.5, howl: 0.3, gain: 0.58 }), { type: 'machine', kind: 'gears', rate: 0.9, gain: 0.06 }, { type: 'music', kind: 'accordion', tune: 'waltz', detune: 20, wow: 0.5, gain: 0.05, pos: [0, 4, 25], gap: [6, 20] }, { type: 'noise', color: 'pink', lp: 500, mod: 0.08, depth: 0.3, gain: 0.15 } ],
    events: [{ type: 'radio', every: [20, 50] }, { type: 'creak', every: [8, 20] }, { type: 'wolf', every: [50, 120], pos: 'far' }, { type: 'ice-crack', every: [30, 80] }, { type: 'whistle', every: [40, 90], pos: 'far' }, { type: 'clank', every: [15, 40], pos: 'far' }, { type: 'scream-far', every: [90, 200], pos: 'far', gain: 0.6 }] },
  'whiteout.station': { space: 'whiteoutStation', gain: 0.557, rooms: [{ space: 'snow', meanMin: 18, ceilMin: 25 }], eventGain: 0.8, beds: [
    { type: 'machine', kind: 'motor', rpm: 900, whine: 900, gain: 0.14 }, { type: 'machine', kind: 'gears', rate: 1.1, gain: 0.1 }, { type: 'hum', freq: 30, harmonics: 14, buzz: 0.3, gain: 0.08 }, W({ speed: 0.55, gust: 0.6, whistle: 0.3, howl: 0.55, gain: 0.3 }), { type: 'noise', color: 'white', hp: 3000, mod: 0.12, depth: 0.5, gain: 0.09 } ],
    events: [{ type: 'clank', every: [6, 16] }, { type: 'creak', every: [5, 14] }, { type: 'radio', every: [25, 60] }, { type: 'bell', every: [40, 90], pos: 'far', gain: 0.6 }, { type: 'chain', every: [14, 36] }, { type: 'pipe', every: [20, 50] }, { type: 'metal-groan', every: [20, 50] }] },
  'whiteout.summit': { space: 'summit', gain: 0.229, eventGain: 3, beds: [
    W({ speed: 0.95, gust: 0.9, whistle: 0.8, howl: 0.5, gain: 0.62 }), { type: 'crackle', kind: 'ice', intensity: 0.6, gain: 0.5 }, { type: 'machine', kind: 'clock', rpm: 60, gain: 0.25 }, { type: 'drone', freq: 220, chord: [1, 1.5, 2.02], movement: 0.7, bright: 6000, detune: 12, gain: 0.12 } ],
    events: [{ type: 'ice-crack', every: [15, 45] }, { type: 'thunder', every: [50, 110], pos: 'far', gain: 0.8 }, { type: 'ping', every: [10, 25], gain: 0.6 }, { type: 'beep', every: [12, 30], gain: 0.6 }, { type: 'gust', every: [6, 14], gain: 0.8 }, { type: 'wolf', every: [40, 100], pos: 'far', gain: 0.6 }] },
  // ------------------------------------------------------------------------------------------------ LAST FERRY
  'last-ferry.pier': { space: 'pier', gain: 0.422, rooms: [{ space: 'warehouse', meanMax: 9, ceilMax: 8 }], eventGain: 2, beds: [
    { type: 'water', kind: 'lap', intensity: 0.5, gain: 0.36 }, W({ speed: 0.3, gust: 0.3, whistle: 0.1, howl: 0.1, gain: 0.2 }), { type: 'machine', kind: 'diesel', rpm: 700, gain: 0.06 }, { type: 'rumble', freq: 110, throb: 0, gain: 0.3 }, { type: 'noise', color: 'pink', lp: 800, mod: 0.05, depth: 0.3, gain: 0.15 } ],
    events: [{ type: 'foghorn', every: [20, 50] }, { type: 'gull', every: [4, 12] }, { type: 'bell', every: [18, 45], pos: 'far', gain: 0.55 }, { type: 'creak', every: [5, 14] }, { type: 'wood-knock', every: [20, 50] }, { type: 'splash', every: [15, 40] }, { type: 'whistle', every: [50, 110], pos: 'far', gain: 0.6 }] },
  'last-ferry.wharf': { space: 'wharf', gain: 0.67, rooms: [{ space: 'warehouse', meanMax: 10, ceilMax: 9 }], eventGain: 0.8, beds: [
    { type: 'water', kind: 'lap', intensity: 0.6, gain: 0.3 }, { type: 'machine', kind: 'compressor', rpm: 60, gain: 0.12 }, { type: 'machine', kind: 'generator', rpm: 1100, gain: 0.07 }, W({ speed: 0.25, gust: 0.35, whistle: 0.1, howl: 0.05, gain: 0.14 }), { type: 'noise', color: 'pink', bp: 1100, q: 0.5, mod: 0.3, depth: 0.5, gain: 0.45 } ],
    events: [{ type: 'gull', every: [2, 6] }, { type: 'clank', every: [5, 14] }, { type: 'radio', every: [15, 40] }, { type: 'chain', every: [12, 32] }, { type: 'door', every: [18, 45] }, { type: 'scurry', every: [25, 60] }, { type: 'pop', every: [20, 50] }, { type: 'foghorn', every: [50, 110], gain: 0.7 }] },
  'last-ferry.prison': { space: 'prison', gain: 0.67, eventGain: 0.8, beds: [
    W({ speed: 0.5, gust: 0.6, whistle: 0.7, howl: 0.4, gain: 0.32 }), { type: 'water', kind: 'surf', intensity: 0.4, gain: 0.2 }, { type: 'hum', freq: 50, harmonics: 8, buzz: 0.7, gain: 0.07 }, { type: 'machine', kind: 'generator', rpm: 1500, gain: 0.09 } ],
    events: [{ type: 'chain', every: [8, 20] }, { type: 'clank', every: [10, 25] }, { type: 'scream-far', every: [40, 100], pos: 'far', gain: 0.7 }, { type: 'siren', every: [90, 180], pos: 'far', gain: 0.6 }, { type: 'radio', every: [20, 50] }, { type: 'gull', every: [12, 30] }, { type: 'bell', every: [30, 70], pos: 'far', gain: 0.6 }, { type: 'door', every: [25, 60] }, { type: 'metal-groan', every: [20, 50] }] },
  'last-ferry.lighthouse': { space: 'lighthouse', gain: 0.317, eventGain: 2, beds: [
    { type: 'water', kind: 'surf', intensity: 1.0, gain: 0.55 }, W({ speed: 0.72, gust: 0.8, whistle: 0.4, howl: 0.3, gain: 0.42 }), { type: 'machine', kind: 'gears', rate: 0.6, gain: 0.05 }, { type: 'machine', kind: 'motor', rpm: 300, whine: 500, gain: 0.04 } ],
    events: [{ type: 'gull', every: [3, 9] }, { type: 'foghorn', every: [35, 80] }, { type: 'thunder', every: [30, 80], pos: 'far' }, { type: 'bell', every: [40, 90], pos: 'far', gain: 0.6 }, { type: 'creak', every: [10, 25] }, { type: 'splash', every: [10, 25] }] },
  // ------------------------------------------------------------------------------------------------ AFTER HOURS
  'after-hours.plaza': { space: 'plaza', gain: 1.41, rooms: [{ space: 'hutInterior', meanMax: 6, ceilMax: 7 }], eventGain: 0.8, beds: [
    { type: 'music', kind: 'calliope', tune: 'carousel', detune: 22, wow: 0.6, gain: 0.34, gap: [1, 4], pos: [20, 3, -25] }, { type: 'noise', color: 'pink', bp: 900, q: 0.5, mod: 0.4, depth: 0.5, gain: 0.15 }, W({ speed: 0.15, gust: 0.2, whistle: 0, howl: 0.05, gain: 0.07 }), { type: 'hum', freq: 60, harmonics: 8, buzz: 0.5, gain: 0.03 } ],
    events: [{ type: 'laugh-far', every: [12, 35] }, { type: 'firework', every: [25, 70], pos: 'far' }, { type: 'radio', every: [18, 45] }, { type: 'ping', every: [8, 22] }, { type: 'bell', every: [30, 80], pos: 'far', gain: 0.5 }, { type: 'scream-far', every: [50, 120], pos: 'far', gain: 0.6 }, { type: 'whistle', every: [40, 90] }, { type: 'pop', every: [10, 30] }, { type: 'blip', every: [6, 18] }] },
  'after-hours.space': { space: 'space', gain: 1.386, eventGain: 0.35, beds: [
    { type: 'music', kind: 'synth', tune: 'space', detune: 8, wow: 0.2, gain: 0.2, gap: [2, 6] }, { type: 'hum', freq: 60, harmonics: 10, buzz: 0.3, color: 0.7, gain: 0.07 }, { type: 'machine', kind: 'fan', rpm: 900, gain: 0.07 }, { type: 'drone', freq: 82, chord: [1, 1.5, 2, 2.997], movement: 0.7, bright: 3200, gain: 0.09 } ],
    events: [{ type: 'blip', every: [3, 9] }, { type: 'zap', every: [10, 28] }, { type: 'ping', every: [8, 20] }, { type: 'radio', every: [20, 50] }, { type: 'beep', every: [6, 16] }, { type: 'siren', every: [80, 160], pos: 'far', gain: 0.5 }, { type: 'laugh-far', every: [40, 90], gain: 0.5 }, { type: 'moan-far', every: [60, 130], gain: 0.5 }] },
  'after-hours.castle': { space: 'castle', gain: 0.55, rooms: [{ space: 'openDusk', meanMin: 14, ceilMin: 25 }], eventGain: 0.5, beds: [
    { type: 'music', kind: 'organ', tune: 'dirge', detune: 12, wow: 0.3, gain: 0.22, gap: [3, 10] }, W({ speed: 0.45, gust: 0.6, whistle: 0.35, howl: 0.75, gain: 0.3 }), { type: 'drone', freq: 55, chord: [1, 1.19, 1.5], movement: 0.6, bright: 900, gain: 0.09 }, { type: 'water', kind: 'drip', rate: 0.5, gain: 0.7 } ],
    events: [{ type: 'creak', every: [4, 10] }, { type: 'thunder', every: [30, 80], pos: 'far' }, { type: 'bell', every: [25, 60] }, { type: 'scream-far', every: [40, 100], pos: 'far', gain: 0.7 }, { type: 'laugh-far', every: [45, 110], gain: 0.7 }, { type: 'chain', every: [12, 30] }, { type: 'door', every: [20, 50] }, { type: 'moan-far', every: [20, 50] }, { type: 'owl', every: [25, 60] }, { type: 'wood-knock', every: [15, 40] }, { type: 'metal-groan', every: [30, 70] }] },
  'after-hours.cove': { space: 'cove', gain: 0.633, eventGain: 1, beds: [
    { type: 'water', kind: 'lap', intensity: 0.6, gain: 0.3 }, { type: 'water', kind: 'surf', intensity: 0.5, gain: 0.24 }, W({ speed: 0.4, gust: 0.5, whistle: 0.2, howl: 0.1, gain: 0.2 }), { type: 'music', kind: 'accordion', tune: 'shanty', detune: 26, wow: 0.6, gain: 0.26, gap: [3, 9], pos: [-15, 3, 20] } ],
    events: [{ type: 'gull', every: [3, 9] }, { type: 'creak', every: [4, 10] }, { type: 'clank', every: [8, 20] }, { type: 'cannon', every: [60, 140], pos: 'far' }, { type: 'parrot', every: [12, 30] }, { type: 'splash', every: [10, 25] }, { type: 'bell', every: [40, 90], pos: 'far', gain: 0.5 }, { type: 'scream-far', every: [40, 90], pos: 'far', gain: 0.6 }, { type: 'laugh-far', every: [50, 120], gain: 0.5 }] },
  // ------------------------------------------------------------------------------------------------ menu
  menu: { space: 'open', gain: 1.65, eventGain: 1, beds: [{ type: 'drone', freq: 65, chord: [1, 1.5, 2, 3], movement: 0.6, bright: 2200, gain: 0.16 }, { type: 'music', kind: 'musicbox', tune: 'lullaby', detune: 14, wow: 0.3, gain: 0.16, gap: [4, 12] }, W({ speed: 0.15, gust: 0.2, gain: 0.08, follow: false })], events: [{ type: 'chime', every: [8, 20], gain: 0.6 }, { type: 'creak', every: [12, 30], gain: 0.5 }, { type: 'drip', every: [10, 25], gain: 0.5 }] },
};
for (const r of Object.values(PRESETS)) r.cal = true; // level-calibrated by tools/audio-analyze.mjs (stop-authored recipes get an automatic trim instead)
const ALIAS = {
  surface: 'shaft-nine.surface', yard: 'shaft-nine.surface', collar: 'shaft-nine.surface', tunnels: 'shaft-nine.tunnels', tunnel: 'shaft-nine.tunnels', timbered: 'shaft-nine.tunnels', drift: 'shaft-nine.tunnels', flooded: 'shaft-nine.flooded', flood: 'shaft-nine.flooded', crystal: 'shaft-nine.crystal', cavern: 'shaft-nine.crystal', magma: 'shaft-nine.magma', lava: 'shaft-nine.magma',
  village: 'whiteout.village', base: 'whiteout.village', station: 'whiteout.station', mid: 'whiteout.station', midmountain: 'whiteout.station', summit: 'whiteout.summit', observatory: 'whiteout.summit',
  pier: 'last-ferry.pier', city: 'last-ferry.pier', wharf: 'last-ferry.wharf', market: 'last-ferry.wharf', fish: 'last-ferry.wharf', prison: 'last-ferry.prison', island: 'last-ferry.prison', lighthouse: 'last-ferry.lighthouse', rock: 'last-ferry.lighthouse',
  plaza: 'after-hours.plaza', entrance: 'after-hours.plaza', space: 'after-hours.space', spaceage: 'after-hours.space', castle: 'after-hours.castle', haunted: 'after-hours.castle', cove: 'after-hours.cove', pirate: 'after-hours.cove',
};
/** name (exact preset, stop id, or any recognisable fragment) -> recipe */
export function resolvePreset(name) {
  if (PRESETS[name]) return PRESETS[name]; const k = String(name).toLowerCase().replace(/[^a-z.]/g, '').replace(/^.*\./, (m) => m); const flat = String(name).toLowerCase().replace(/[^a-z]/g, '');
  for (const key of Object.keys(PRESETS)) if (key.toLowerCase().replace(/[^a-z]/g, '') === flat) return PRESETS[key];
  const last = String(name).toLowerCase().split(/[.:/]/).pop().replace(/[^a-z]/g, ''); if (ALIAS[last]) return PRESETS[ALIAS[last]]; if (ALIAS[flat]) return PRESETS[ALIAS[flat]];
  for (const [a, id] of Object.entries(ALIAS)) if (flat.includes(a)) return PRESETS[id]; return null;
}
